name: k6

on:
  workflow_dispatch:
    inputs:
      target_sut:
        required: true
        description: run test against this base url
      type:
        required: true
        description: test to run
        type: choice
        options:
          - smoke.js

permissions:
  contents: write # permission to write to GitHub pages

defaults:
  run:
    shell: bash

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: run k6
        env:
          SUT: ${{ inputs.target_sut }}
        run: |
          cd loadtest
          mkdir results
          k6 run ${{ inputs.type }} --summary-export summary.json

      - name: test summary
        uses: ./.github/actions/k6-summary
        with:
          summary_file: loadtest/summary.json
          title: "K6 summary"

      - name: upload test result to Github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: loadtest/results

